name = 'container system'

[environment-variables]
SOME_VAR = 'SOME_VAL'
SOME_VAR2 = 'SOME_VAL2'

[[machine]]
name = "application"
bin = "application.sh"
    [machine.provider.container]
    containerfile = 'Containerfile'
    image = "foo"
    volume = "conf/:/app/conf/"
