FROM docker.io/ubuntu:jammy

ENV NVIDIA_VISIBLE_DEVICES \
   ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
   ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    vim \
    wget \
    pkg-config \
    screen \
    policykit-1 \
    libc6-dev \
    python3 \
    python3-pip \
    iproute2 \
    bridge-utils

RUN apt-get install -y gpg-agent software-properties-common

RUN add-apt-repository -y ppa:savoury1/ffmpeg4
RUN add-apt-repository -y ppa:savoury1/virtualisation
RUN apt-get update && apt-get install -y qemu-system-arm qemu-system-s390x qemu-system-x86 qemu-efi qemu-utils cloud-image-utils
