FROM docker.io/ubuntu:jammy

ENV NVIDIA_VISIBLE_DEVICES \
   ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
   ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    vim \
    wget \
    pkg-config \
    gtk-sharp2 \
    screen \
    policykit-1 \
    libc6-dev \
    gcc \
    python3 \
    python3-pip\
    mono-complete

RUN wget https://github.com/renode/renode/releases/download/v1.13.3/renode_1.13.3_amd64.deb -O /renode.deb
RUN apt-get install -y /renode.deb

RUN apt-get install -y iproute2 bridge-utils
